Features/secure routes
irenesuarezalvarez/talk-clinical-management pull request #7
Opened 2021-08-27 00:12 UTC by irenesuarezalvarez

2021-08-27 12:41 UTC, michaelkoek requested changes

2021-08-27 12:41 UTC, michaelkoek commented on src/App.js
> +import CreateCloudi from "./pages/patients/Create-Cloudinary";
`CreateCloudi` is a weird name. Can you give a more descriptive name?

2021-08-27 12:41 UTC, michaelkoek commented on src/App.js
> +          <Route path="/createclou">
What can you do at this route that you've named it `createclou`? What is a "clou"?

2021-08-27 12:41 UTC, michaelkoek commented on src/App.js
> +import PrivateProf from "./utils/PrivateProf";
If this is a private route, maybe rename it to `PrivateRoute` instead of `PrivateProf`, which makes it more descriptive. The utility should describe what's it doing and not giving a description of your application. Your util doesn't need to know about the topic of your application. All it needs to do is to secure the route

2021-08-27 12:41 UTC, michaelkoek commented on src/App.js
>              <Create/>
Give this component a better name "create"; create what? 
Based on the signup path you could call it `SignUpPage` maybe?

2021-08-27 12:41 UTC, michaelkoek commented on src/App.js
> +            <Details/>
Rename this to `DetailsPage` so it's more descriptive that this component is a page.
Matter of fact; do that with all the pages component. Add `Pages` after it so it's clear what it is

2021-08-27 12:41 UTC, michaelkoek commented on src/Calendar.css
> +@import "../node_modules/@syncfusion/ej2-react-schedule/styles/material.css";
Never use packages like this. This is not the way it's intended.
It should be something like this (but you have to verify in the documentation as you choose to use this)

```javascript
import { DateRangePicker, DatePicker, TimePicker, RangeEventArgs } from '@syncfusion/ej2-calendars';
```
(I copy/pasted this from the example code you can find in the docs)

2021-08-27 12:41 UTC, michaelkoek commented on src/Calendar.css
> +} */
If you're not going to use this, remove all the commented code in your repo.
If you want to hold it for later use, add a comment so that the user knows that you're planning in using it later

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Box-Row.js
> +`;
If this is the only thing that is different with the `BoxCenter` component, why not make 1 component and pass props to change how you want it, for example something like this:

```javascript
// direction (on the rightside) is a prop (string) being passed to this component
// isCentered  is a prop (boolean) being passed to this component

<Box direction={direction} center={isCenter}>
   {children}
</Box>

const Box = styled.section`
  display: flex;
  flex-direction: ${({direction}) => direction === 'row' ? 'row' : 'column'};
 ${({ center }) => center && css`
    justify-content: center;
    align-items: center;
`}
  border-radius: 5px;
`
```

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/BtnDiv.js
> +function BtnDiv ({children}) {
What does this component do? Don't give it the name of the element (div), rather describe what it does.
Is it maybe a container that holds a bunch of buttons? Maybe `ButtonContainer` is a better name

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/BtnDiv.js
> +function BtnDiv ({children}) {
Why not reuse the `Box` component, which practically does the same?

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Button.js
> +        background-color: rgb(45, 167, 175);
Store all these colors in the theme, which you can than easily use like this: `${props => props.theme.main};`

ref: https://styled-components.com/docs/advanced#theming

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Button.js
> +        background-color: rgb(45, 167, 175);
Note: This comment applies to everywhere where you have colors, so not only this one

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Button.js
> +margin-bottom: 1rem;
Use here indentation

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Card.js
> +  box-shadow: 0 0 20px rgb(0 0 0 / 15%);
use `rgba()` instead of `rgb`. That also means you have to change the syntax a bit

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Navbar.js
> +import React, { useContext, useState } from "react"; //useState deleted
Remove all the comments

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Navbar.js
> +  const [redirect, setRedirect] = useState(false);
Nitpicky: Move this line one up so that the context variables are close to each other. Makes it more organised

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Navbar.js
> +  /* const history = useHistory() */
Remove this

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Navbar.js
> +      await logOut()
If correct; in the backend you have set a response. Catch that reponse and based on that you do the redirect
so:

```javascript
 const data = await logOut();
 const result = data.status
setRedirect(result === 200) // better to use an expression

```

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Navbar.js
> +  console.log('redirectttttt', redirect)
Remove the console log. Nog console log in the repo. You only use it for development purposes

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Navbar.js
> +/*   const handleLogOut = async event => {
Remove this

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Navbar.js
> +  console.log('Cambio??', role)
remove this

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Navbar.js
> +        {/*   { isAuth && <li><Button onClick={handleLogOut}>Log out</Button></li>} */}
Remove this

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Navbar.js
> +          <li><StyledLink to="/createclou">Clou</StyledLink></li>
What is a `Clou`?

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Navbar.js
> +          <li><StyledLink to="/create">Create</StyledLink></li>
Create what?

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Navbar.js
> +  margin:5px 25px ;
Add space between the property and the value

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Search.js
> +const Searcher = ({}) => {
Why do you have `{}` as the argument?

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Search.js
> +        console.log('search clicked')
Remove this

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Search.js
> +            console.log('New patient was found', data.data)//data.data devuelve un []
Remove this

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Search.js
> +        return searchPatients && searchPatients.map(({ _id, surname, name }) => {
You should check if the array is filled: `searchPatients.length && ...`

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Search.js
> +                        {/* <BoxButtonRight onClick={() => deletePatient(_id)}><FontAwesomeIcon icon={faTrashAlt} /></BoxButtonRight> */}
Remove this

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Search.js
> +                            <IconDiv><FontAwesomeIcon icon={faSearch} /></IconDiv>
Add correct indentation to this page

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Search.js
> +                                type = "text"
An attribute doesn't have any space. Remove all the spaces around the attribute. One example is:

``` javascript
// don't
type = "text"
type= "text"

// do
type="text"
```

2021-08-27 12:41 UTC, michaelkoek commented on src/components/layouts/Search.js
> +    justify-content:space-around;
space between property and value (happens on more places in this file)

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/authentication/Login.js
> +        setRedirect(true)
and also check your spacing on this line `const data =  await  logIn(checkUser);` 
Please keep your code clean and consistent

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/authentication/Login.js
> +  } */
Remove comment

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/authentication/Login.js
> +  console.log('este es el role', role)
Remove console log

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/authentication/Login.js
> +    console.log('entra again')
Remove console log

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/authentication/Login.js
> +  }else if(redirect && role === "admin"){
Add space `} else`

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/authentication/Login.js
> +          type = "text"
Remove spacing (all attributes)

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/authentication/Login.js
> +        <Button type="submit" >Log in</Button>
Remove space before `>`

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/authentication/Signup.js
> +  }else if(redirect && role === "admin"){
space `} else`

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/authentication/Signup.js
> +            <BtnDiv>
Why do you need a whole component for this?

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/general/Home.js
> +    margin-bottom: 2rem;
Indent

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/general/Home.js
> +    height: 100vh;
Why not `100%`?

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/general/Home.js
> +    padding: 1rem 2 rem;
Why do you have a space `2 rem`?

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/patients/Clinical-history.js
> +        axiosApi.delete(`${URL}/${id}`).then(res => {
Use `async/await` to be consistent

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/patients/Create-Cloudinary.js
> +    const fetchUsers = async () => {
indent

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/patients/Create-Cloudinary.js
> +    const { name, value } = event.target;
indent

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/patients/Create-Cloudinary.js
> +    const { name, value } = event.target;
This applies to all your code: everything inside of the function body is always indented:

```javascript
const myFunction = () => {
    // indented body
    console.log('hi')
}

```

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/patients/Create-Cloudinary.js
> +      await axiosApi.post('/patients/create', newPatient)
```javascript
const data =  await axiosApi.post('/patients/create', newPatient)
setRedirect() // use here status 200 to redirect 
```

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/patients/Create-Cloudinary.js
> +    return <Redirect to='/patients'></Redirect>
`<Redirect to='/patients' />`

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/patients/Create-Cloudinary.js
> +                {/* <input type="file" name="image" id="" /> */}
Remove this

2021-08-27 12:41 UTC, michaelkoek commented on src/pages/patients/Create-Cloudinary.js
> +
Why so much space?

2021-08-27 13:24 UTC, irenesuarezalvarez commented on src/App.js
> +import CreateCloudi from "./pages/patients/Create-Cloudinary";
This is just a test, I'll change it later on. It was just to differenciate it from the Create component, but it would later replace it

2021-08-27 13:47 UTC, irenesuarezalvarez commented on src/App.js
>              <Create/>
I changed it to CreatePatient

2021-08-27 13:56 UTC, irenesuarezalvarez commented on src/pages/patients/Create-Cloudinary.js
> +                {/* <input type="file" name="image" id="" /> */}
Still working on this

2021-08-27 13:56 UTC, irenesuarezalvarez commented on src/pages/patients/Create-Cloudinary.js
> +
Still working on this page

2021-08-27 14:16 UTC, irenesuarezalvarez commented on src/Calendar.css
> +@import "../node_modules/@syncfusion/ej2-react-schedule/styles/material.css";
I just copy paste this from their documentation, it was very tough to have this working in the code I'm not sure how to import this in another way, there are from different files

2021-08-27 14:16 UTC, irenesuarezalvarez commented on src/Calendar.css
> +} */
Still working on this

2021-08-27 14:34 UTC, michaelkoek commented
This is a comment for the future/next time:
If this branch is called "secureRoutes" I would expect to see only code regarding secure routes . This PR is way to big to be a feature

2021-08-27 14:37 UTC, michaelkoek commented
Also, to avoid all of this indentation remarks, please, as your next ticket, add Prettier to the stack. So it can format the code on saving the file and you don't have to think about it

2021-08-27 14:37 UTC, michaelkoek commented on src/App.js
> +import CreateCloudi from "./pages/patients/Create-Cloudinary";
Next time if you're testing things or have elements that are temporary, add a comment so that the reviewer knows

2021-08-27 15:13 UTC, irenesuarezalvarez commented on src/components/layouts/Box-Row.js
> +`;
That is I good idea! I'm just having an error saying css is not define.

2021-08-27 15:20 UTC, irenesuarezalvarez commented on src/components/layouts/Navbar.js
> +  /* const history = useHistory() */
Here I'm having problems while redirecting after doing the log out. It renders the component I redirect too but it does not render the navbar. (I read in stackoverflow that it was related to the useHistory and at some point this was working.. not anymore but I have it there commented as its not solved

2021-08-27 15:23 UTC, michaelkoek requested changes

2021-08-27 15:23 UTC, michaelkoek commented on src/components/layouts/Card.js
> +export const Title = styled.h2`
Why do you export this? I assume this Title is only for this component. If you want to reuse this style, than abstract it to a separate file and import it in the files where you need it

2021-08-27 15:23 UTC, michaelkoek commented on src/components/layouts/Navbar.js
> +
Nitpick: Remove all of the extra enters. Keep your code nice and clean

2021-08-27 15:23 UTC, michaelkoek commented on src/components/layouts/Navbar.js
> +        <Link to="/"><StyledLogo  src="../images/EasyClinicLogo.png" alt="Easy Clinic Logo"></StyledLogo></Link>
Remove the extra space before the `src` tag

2021-08-27 15:23 UTC, michaelkoek commented on src/components/layouts/Search.js
> +
Remove this space

2021-08-27 15:23 UTC, michaelkoek commented on src/components/layouts/Search.js
> +import { useState } from "react";
Try to have react import always first (just for convention)

2021-08-27 15:23 UTC, michaelkoek commented on src/components/layouts/Search.js
> +                        <BoxButtonLeft to="/calendar"><FontAwesomeIcon icon={faCalendar} /></BoxButtonLeft>
Nitpicky: For readability spread it over two lines:
```javascript
<BoxButtonLeft to="/calendar">
     <FontAwesomeIcon icon={faCalendar} />
</BoxButtonLeft>
```

2021-08-27 15:23 UTC, michaelkoek commented on src/components/layouts/Search.js
> +    box-shadow: 0 0 20px rgb(0 0 0 / 15%);
1: Change the value from `rgb` to `rgba`
2: Add the value `0 0 20px rgb(0 0 0 / 15%);` to the theme as you are using it in multiple places

2021-08-27 15:23 UTC, michaelkoek commented on src/components/layouts/StyledLink.js
> +  background-color: rgb(102, 205, 170);
use everywhere `rgba` or `hex` to stay consistent

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/authentication/Login.js
> +           if(data.status === 200){
Check your indentations

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/authentication/Signup.js
> +  const createUser =  event => {
Remove the extra space before `event`

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/general/Calendar.js
> +  var scheduleObj = new Schedule();
Never use `var` 🚫

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/general/Calendar.js
> + /*  const data = [{
Do you still need this? Remove it

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/general/Calendar.js
> +const prof1 =[{
Looks like data that should come from the backend?

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/general/Calendar.js
> +    return collections;
I think this whole function can be reduced to this:
```javascript
return [
  ...mycalendar,
  ...prof1,
  ...prof2,
  ...prof3
];
```
But obviously verify

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/general/Calendar.js
> +    console.log('value', value)
Remove this

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/general/Calendar.js
> +            <td style={{ width: '100%' }}>
No inline styling. Never

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/general/Calendar.js
> +        <tr style={{ height: '50px' }}>
No inline styling. Never

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/general/Calendar.js
> +                <CheckBoxComponent value='1' id='holidays' checked={false} label='John' change={onChange.bind(this)}></CheckBoxComponent>
Why are you binding to `this`? `onChange.bind(this)`

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/general/Calendar.js
> +
You have a open and close tag for `ResourceDirective` but nothing in-between.
If this is the case just have a self-closing tag like this: `<ResourceDirective />`

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/general/Calendar.js
> +  padding: 1rem 1rem;
`padding: 1rem;` is enough

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/general/Calendar.js
> +            field='ResourceId'
Use double quotes (consistency)  `field="ResourceId" `

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/general/Calendar.js
> +            allowMultiple={true}
Is the value is `true` you don't have to add `={true}`, so only this is enough `allowMultiple`

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/general/Calendar.js
> +  box-shadow: 0 0 20px rgb(0 0 0 / 15%);
Grab this from the theme (as you have this in multiple places)

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/general/Home.js
> +         <StyledLogo src="../images/EasyClinicLogo.png" alt="Easy Clinic Logo"></StyledLogo>
self closing element `<StyledLogo />`

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/general/Home.js
> +            <DivSignUp>
Indentation:
```javascript
<DivSignUp>
     <span>I don't have an account</span>
     <StyledLink to="/signup">Sign up</StyledLink>
</DivSignUp>
```

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/general/Home.js
> +&: hover{
Remove the space and add one before the curly bracket:
```css
&:hover {
```

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/patients/Clinical-history.js
> +        return history && history.map(({ date, notes, content, _id }) => {
Check if the array has an item

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/patients/Clinical-history.js
> +                        <DeleteBtn  onClick={() => deleteSession(_id)}><FontAwesomeIcon icon={faTrashAlt} /></DeleteBtn>
1: Remove the extra space after `DeleteBtn`
2: Split over multiple lines for better readability

```javascript
<DeleteBtn onClick={() => deleteSession(_id)}>
  <FontAwesomeIcon icon={faTrashAlt} />
</DeleteBtn>
```

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/patients/Clinical-history.js
> +const StyledInput = styled.input`
I remember you having this styling else where to. Maybe abstract it and import it where needed

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/patients/Create-Cloudinary.js
> +                            {professional.username}
Indent

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/patients/Details-patient.js
> +        const { name, surname, email, phone, address, city, state, postal, contactname, contactsurname, contactemail, contactphone, professional } = patient;
Put each property on a new line so it's easier to read:
```javascript
const { 
   name, 
   surname,
   email, 
   phone,
   //..etc
```

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/patients/Details-patient.js
> +                                            <p>{name}</p>
These aren't paragraphs. Paragraphs are multiple lines of text. I would say it should be a `<span>`
ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/patients/Details-patient.js
> +    box-shadow: 0 0 20px rgb(0 0 0 / 15%);
All box shadows are the same so this should come from the Theme

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/patients/List-all-patients.js
> +/* import { faSearch } from '@fortawesome/free-solid-svg-icons' */
Remove this

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/patients/List-all-patients.js
> +        axiosApi.delete(`${URL}/${id}`).then(res => {
Use `async/await`

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/patients/List-all-patients.js
> +                        <BoxButtonLeft to="/calendar"><FontAwesomeIcon icon={faCalendar} /></BoxButtonLeft>
All elements that are in between other elements should be on a new line.
e.g:

```javascript
<BoxButtonLeft to="/calendar">
  <FontAwesomeIcon icon={faCalendar} />
</BoxButtonLeft>
```

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/patients/List-all-patients.js
> +               {/*  //NEWWWWWWWWWWWWWWWWWWWWWW */}
Remove all comments

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/patients/List-all-patients.js
> +
You have nothing in between here, so should be a self closing element

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/patients/List-all-patients.js
> +    background-color: secondary_light;
where does this come from `secondary_light`? This color should come from the Theme

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/patients/List-all-patients.js
> +    background-color: lightgrey;
Color should be in theme; unless you're using it only once

2021-08-27 15:23 UTC, michaelkoek commented on src/pages/patients/List-my-patients.js
> +   /*  const removeData = (id) => {
Delete all comments from this file

2021-08-27 15:23 UTC, michaelkoek commented on src/utils/AuthContext.js
> +     return data
Why are you returning `data`?

2021-08-27 15:23 UTC, michaelkoek commented on src/utils/AuthContext.js
> +      setRole(data.data.role);
I would say this goes inside the `if` statement

2021-08-27 15:23 UTC, michaelkoek commented on src/utils/AuthContext.js
> +        setIsAuth(true);
Could be `setIsAuth(data.status === 200)`

2021-08-27 15:23 UTC, michaelkoek commented on src/utils/AuthContext.js
> +      if(data.status === 200){
Could be `setIsAuth(data.status === 200)`

2021-08-27 15:23 UTC, michaelkoek commented on src/utils/AuthContext.js
> +      console.log('aqui deberia tener el user de req session', data.data._id, data.status )
Remove

2021-08-27 15:23 UTC, michaelkoek commented on src/utils/PrivateRoute.js
> +  console.log('ENTRAAA?? Front end private routes js12', role)
Remove

2021-08-27 15:23 UTC, michaelkoek commented on src/utils/PrivateRoute.js
> +    return    <Route {...props}>{children}</Route>
Too much space after `return`. One space is enough

2021-08-27 15:23 UTC, michaelkoek commented on src/utils/PrivateRoute.js
> +    return  <Redirect
Too much space after `return`. One space is enough

2021-08-27 15:23 UTC, michaelkoek commented on src/utils/PrivateRoute.js
> +  if(role === undefined){
`if (!role) {` is better

2021-08-27 15:23 UTC, michaelkoek commented on src/utils/PrivateRoute.js
> +/*   return isAuth ? (
Remove

2021-08-27 15:25 UTC, irenesuarezalvarez commented on src/components/layouts/Navbar.js
> +  console.log('Cambio??', role)
redirect does not work after the log out for admin positions

2021-08-27 15:25 UTC, irenesuarezalvarez commented on src/components/layouts/Navbar.js
> +        {/*   { isAuth && <li><Button onClick={handleLogOut}>Log out</Button></li>} */}
Still working on it

2021-08-27 15:27 UTC, irenesuarezalvarez commented on src/components/layouts/Navbar.js
> +          <li><StyledLink to="/create">Create</StyledLink></li>
Changed for /createpatient

2021-08-27 15:28 UTC, irenesuarezalvarez commented on src/components/layouts/Search.js
> +const Searcher = ({}) => {
removed

2021-08-27 15:34 UTC, irenesuarezalvarez commented on src/components/layouts/Card.js
> +export const Title = styled.h2`
I'm exporting it as I'm using it in the Details page. I wanted to use Card on a left position so I exported the styles and as I was losing the title styles I had to export Title. Maybe I can change it adding props to Card to be able to position it on the left side. (but I need to figure it out how props works on style components)

2021-08-27 15:39 UTC, irenesuarezalvarez commented on src/App.js
> +          <Route path="/createclou">
still working on it

2021-08-27 15:45 UTC, irenesuarezalvarez commented on src/components/layouts/BtnDiv.js
> +function BtnDiv ({children}) {
I'll review this, yes. Maybe adding padding and margin props it can work

2021-08-27 15:47 UTC, irenesuarezalvarez commented on src/components/layouts/Navbar.js
> +import React, { useContext, useState } from "react"; //useState deleted
I need to solve logout redirect, I'm keeping them just for now, just in case

2021-08-27 15:49 UTC, irenesuarezalvarez commented on src/components/layouts/Navbar.js
> +  const [redirect, setRedirect] = useState(false);
not sure which line you were refering to but I solve it this way:
  const contextAuth = useContext(AuthContext)
  const { isAuth, logOut, role, setRole } = contextAuth;
  const [redirect, setRedirect] = useState(false);

2021-08-27 15:50 UTC, michaelkoek commented on src/components/layouts/Navbar.js
> +  const [redirect, setRedirect] = useState(false);
Yes, that's what I meant 👏 👍

2021-08-27 16:00 UTC, irenesuarezalvarez commented on src/components/layouts/Search.js
> +                        {/* <BoxButtonRight onClick={() => deletePatient(_id)}><FontAwesomeIcon icon={faTrashAlt} /></BoxButtonRight> */}
No its commented because if I uncomment it it does not work. I need to figure this out, I dont know how to send the id to the allpatients page and make deletePatient work

2021-08-27 16:06 UTC, irenesuarezalvarez commented on src/pages/authentication/Login.js
> +  console.log('este es el role', role)
Still working on it for the redirect logout

2021-08-27 16:10 UTC, irenesuarezalvarez commented on src/pages/authentication/Signup.js
> +            <BtnDiv>
Its for the styling , I 'll work on it to see if I can add props to the Box container and use this one

2021-08-27 16:12 UTC, irenesuarezalvarez commented on src/pages/general/Home.js
> +    padding: 1rem 2 rem;
yes.. haha not good?

2021-08-27 16:55 UTC, irenesuarezalvarez commented on src/pages/general/Calendar.js
> +  var scheduleObj = new Schedule();
I know but I had an error when I changed it to const. I'm grabbing this code from the documentation. Still working on it

2021-08-27 16:56 UTC, irenesuarezalvarez commented on src/pages/general/Calendar.js
> +const prof1 =[{
Yess, still working on this and trying to figure it out :)

2021-08-27 16:57 UTC, irenesuarezalvarez commented on src/pages/general/Calendar.js
> +    return collections;
Still working on it, this should come from the backend in the future

2021-08-27 16:57 UTC, irenesuarezalvarez commented on src/pages/general/Calendar.js
> +            <td style={{ width: '100%' }}>
This is from the documentation too

2021-08-27 16:57 UTC, irenesuarezalvarez commented on src/pages/general/Calendar.js
> +        <tr style={{ height: '50px' }}>
From the documentation

2021-08-27 16:58 UTC, irenesuarezalvarez commented on src/pages/general/Calendar.js
> +                <CheckBoxComponent value='1' id='holidays' checked={false} label='John' change={onChange.bind(this)}></CheckBoxComponent>
From the documentation. It was a class, I tried to change it to a fonction but I'm still working on it

2021-08-27 17:00 UTC, irenesuarezalvarez commented on src/components/layouts/Navbar.js
> +/*   const handleLogOut = async event => {
Still working on it, log out redirect does not work

2021-08-27 17:10 UTC, irenesuarezalvarez commented on src/pages/general/Calendar.js
> + /*  const data = [{
Not sure what sheduleObj is doing as I'm importing it from the model in the documentation, I will try to remove it to see if everything still works.  I need to figure it out

2021-08-27 17:17 UTC, irenesuarezalvarez commented on src/components/layouts/Navbar.js
> +          <li><StyledLink to="/createclou">Clou</StyledLink></li>
Working on it

2021-08-27 17:18 UTC, irenesuarezalvarez commented on src/pages/general/Calendar.js
> +            allowMultiple={true}
Its from the documentation

2021-08-27 17:24 UTC, irenesuarezalvarez commented on src/pages/patients/Details-patient.js
> +        const { name, surname, email, phone, address, city, state, postal, contactname, contactsurname, contactemail, contactphone, professional } = patient;
its gonna generate a lot of unnecessary lines, as I'm doing nothing with this variables but just grabbing them from the patient. Don't you think its easier to read in one line?

2021-08-27 17:30 UTC, irenesuarezalvarez commented on src/pages/general/Calendar.js
> + /*  const data = [{
Yes, I checked it and I still need it to be able to show the different calendars once I check the box on the top

2021-08-27 17:41 UTC, irenesuarezalvarez commented on src/pages/patients/List-all-patients.js
> +/* import { faSearch } from '@fortawesome/free-solid-svg-icons' */
I need to solve the deletePatient from the Search component first

2021-08-27 17:45 UTC, irenesuarezalvarez commented on src/pages/patients/List-all-patients.js
> +               {/*  //NEWWWWWWWWWWWWWWWWWWWWWW */}
Still working on this

2021-08-27 17:45 UTC, irenesuarezalvarez commented on src/pages/patients/List-all-patients.js
> +
Still working on this

2021-08-27 17:46 UTC, irenesuarezalvarez commented on src/pages/patients/List-all-patients.js
> +    background-color: secondary_light;
Still working on this

2021-08-27 17:48 UTC, irenesuarezalvarez commented on src/pages/patients/List-my-patients.js
> +   /*  const removeData = (id) => {
Still working on this

2021-08-28 08:28 UTC, michaelkoek commented on src/pages/general/Calendar.js
> +        <tr style={{ height: '50px' }}>
Still... No inline styling

2021-08-28 08:29 UTC, michaelkoek commented on src/pages/patients/Details-patient.js
> +        const { name, surname, email, phone, address, city, state, postal, contactname, contactsurname, contactemail, contactphone, professional } = patient;
Yes; for a person it's easier to read short words line by line (at least in my experience)

2021-08-28 10:06 UTC, sophiekrag approved these changes

2021-08-28 15:42 UTC, irenesuarezalvarez commented on src/components/layouts/Search.js
> +                        {/* <BoxButtonRight onClick={() => deletePatient(_id)}><FontAwesomeIcon icon={faTrashAlt} /></BoxButtonRight> */}
Solved

2021-08-28 15:42 UTC, irenesuarezalvarez commented on src/pages/authentication/Signup.js
> +            <BtnDiv>
Solved

2021-08-28 16:25 UTC, irenesuarezalvarez commented on src/components/layouts/BtnDiv.js
> +function BtnDiv ({children}) {
Done

2021-08-28 16:25 UTC, irenesuarezalvarez commented on src/pages/general/Home.js
> +    padding: 1rem 2 rem;
solved

2021-08-28 16:26 UTC, irenesuarezalvarez commented on src/components/layouts/Card.js
> +export const Title = styled.h2`
solved

2021-08-28 16:28 UTC, irenesuarezalvarez commented on src/pages/patients/Details-patient.js
> +        const { name, surname, email, phone, address, city, state, postal, contactname, contactsurname, contactemail, contactphone, professional } = patient;
done

2021-08-28 16:29 UTC, irenesuarezalvarez commented on src/pages/patients/List-all-patients.js
> +    background-color: lightgrey;
Working on it

2021-08-28 16:31 UTC, irenesuarezalvarez commented on src/utils/AuthContext.js
> +        setIsAuth(true);
Working on it

2021-08-28 16:33 UTC, irenesuarezalvarez commented on src/pages/patients/Details-patient.js
> +    box-shadow: 0 0 20px rgb(0 0 0 / 15%);
working on it

2021-08-28 16:34 UTC, irenesuarezalvarez commented on src/utils/AuthContext.js
> +      if(data.status === 200){
working on it

2021-08-28 16:35 UTC, irenesuarezalvarez commented on src/pages/patients/List-all-patients.js
> +/* import { faSearch } from '@fortawesome/free-solid-svg-icons' */
Solved

2021-08-28 16:35 UTC, irenesuarezalvarez commented on src/utils/AuthContext.js
> +      setRole(data.data.role);
working on it

2021-08-28 16:38 UTC, merged